[package]
name = "chipeyte_interpreter"
version = "0.1.0"
authors = ["Jens Östlund <jostlund@gmail.com>"]
edition = "2018"

[features]

default = []

logging = ["log"]

[dependencies]
log = { version = "0.4.11", optional = true }
